### ISSUE TITLE
Bug: on rare cases, last letter of the word can wrap to the next line

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [AndroidDeveloperLB/AutoFitTextView#15]
To reproduce:
Run the sample on a screen like of Galaxy S3 , and just choose 3 lines.

Then you will see this:

![device-2015-02-26-202111](https://cloud.githubusercontent.com/assets/5357526/6398552/0e8e2874-bdf5-11e4-8d90-cd86ca8cb64a.png)

**Comment by samskiter** [comment]
I think this is due to a rounding error in the core of the measuring algorithm:

```
for(int i=0;i<layout.getLineCount();i++)
  if(maxWidth<layout.getLineWidth(i))
    maxWidth=(int)layout.getLineWidth(i);
textRect.right=maxWidth;
```

The cast to an int: `(int)layout.getLineWidth(i);` might underestimate maxWidth.

Correct to:

`maxWidth=(int)Math.ceil(layout.getLineWidth(i));`

Might help... ?

**Comment by AndroidDeveloperLB** [comment]
@samskiter no it doesn't help. and BTW, the code is:

          int maxWidth=-1;
          for(int i=0;i<layout.getLineCount();i++)
            if(maxWidth<layout.getLineRight(i)-layout.getLineLeft(i))
              maxWidth=(int)layout.getLineRight(i)-(int)layout.getLineLeft(i);

**Comment by felixendres** [comment]
A workaround that works for me, but isn't universally applicable, is to check the number of admissible breaks (i.e. the occurences of whitespace between words) and set the maxLines parameter accordingly. The in-word break could still happen if the words are of varying length, but I haven't seen that so far.

Just wanted to get this out, as long as there's no real solution. 

Thanks for sharing the code, btw!

**Comment by AndroidDeveloperLB** [comment]
@felixendres I don't understand. Do you have a solution for this?

**Comment by felixendres** [comment]
I'm using the AutoResizeTextView for names. Often had a first name only and the single word would be wrapped. Therefore I forbid the wrapping into more lines than words.

    String text = "Felix"
    AutoResizeTextView av = (AutoResizeTextView) v;
    AutoResizeTextView av = (AutoResizeTextView) v;
    int wordCount = 1 + text.length() - text.replace(" ", "").length();
    int maxLines = av.getMaxLines() < wordCount ? av.getMaxLines() : wordCount;
    av.setMaxLines(maxLines);
    av.setText(text);

Depending on the scenario, one should replace the wordCount algorithm using regexp, but for me this works. Anyway, it doesn't help with the situation in the above image, because the "t" wraps into a line shared with another word. It would help with the string "sample text content" though.

**Comment by AndroidDeveloperLB** [comment]
Too bad. If you find a more general solution, please let me know.

**Comment by paulhickman** [comment]
The problem is because if you create a StaticLayout for a given font size, and supply a maximum width that is less than the width of a single substring of non-breaking characters in the text, then it will create a line break mid-word. 

Set the number of lines to 4 in the sample app, and you can get the "nt" of "Content" to both wrap to the next line in scenarios where during the binary search, it tries a text size that is too large.

When using `layout.getLineLeft()` and `layout.getLineRight()` to determine the `maxWidth` you also need to use `layout.getLineEnd()` to inspect what character is at the end of the line, then see if it is a valid break:

    if (i < layout.LineCount-1)
    {
        int end = layout.getLineEnd(i);
        if (end > 0 && !isValidWordWrap(text[end - 1], text[end])) return 1;
    }

For ASCII English text IsValidWordWrap is trivial - is it a space of hyphen?

    public boolean isValidWordWrap(char before, char after)
    {
        return before ==' ' || before=='-';
    }

For more complex scenarios, you'd need to implement http://unicode.org/reports/tr14, or for a more efficient solution, copy the source code of StaticLayout into your own class, and create a verison that sets a boolean flag when it is forced to wrap mid-word that you can then read back to check if it happened.

**Comment by AndroidDeveloperLB** [comment]
Can you please show a way to solve this, and make a pull request?

**Comment by paulhickman** [comment]
I'm working on a c# port in Xamarin, not the original Java source.

**Comment by AndroidDeveloperLB** [comment]
I think it should be similar. Can you tell me which parts to change, and to
what?

**Comment by paulhickman** [comment]
Put some { } on the `for(int i=0;i<layout.getLineCount();i++)` loop quoted in the 2nd/3rd post and add my 'if' statement inside that loop. Then add the isValidWordWrap as a method on the nested child interface & anonymous class.

As an aside, I'm not sure why you need a interface/anonymous child class to do the hit testing - I just moved the OnTestSize method to an ordinary method on the main class while porting it to save allocating memory for a child object every time a widget is created. However, the code to be modified is the same regardless of which class it is in.

**Comment by AndroidDeveloperLB** [comment]
I don't understand where to put what changes.

**Comment by ViksaaSkool** [comment]
Has anyone managed to solve this? Any updates?

**Comment by AndroidDeveloperLB** [comment]
@ViksaaSkool Sadly no. I can't understand what the above person meant. :(

**Comment by solominh** [comment]
@paulhickman is right
@ViksaaSkool you should find this line for(int i=0;i<layout.getLineCount();i++) and replace that for loop  with the one here:

`int lineCount = layout.getLineCount();
                   for (int i = 0; i < lineCount; i++) {
                        int end = layout.getLineEnd(i);
                        if (i < lineCount - 1) {
                            if (end > 0 && !isValidWordWrap(text.charAt(end - 1), text.charAt(end)))
                                return 1;
                        }

                        if (maxWidth < layout.getLineRight(i) - layout.getLineLeft(i))
                            maxWidth = (int) layout.getLineRight(i) - (int) layout.getLineLeft(i);

                    }`

Then you add isValidWordWrap to the class:

`public boolean isValidWordWrap(char before, char after) {
        return before == ' ' || before == '-';
    }`


Done. Hope it help. :)

**Comment by AndroidDeveloperLB** [comment]
@solominh Yes, this seems to help.
Thank you.
Closing this issue , and making a new release to be available.
