### ISSUE TITLE
Set text size method clarification

### ISSUE THREAD

**Issue by storix** [AndroidDeveloperLB/AutoFitTextView#40]
Hi! Please can you clarify the usage of `setTextSize` method in the sample project [here](https://github.com/AndroidDeveloperLB/AutoFitTextView/blob/master/AutoFitTextViewSample/src/com/example/autofittextviewsample/MainActivity.java#L112). I just can't wrap my head around it. What I need is to auto size a text font in accordance with the given width and height bounds. But according to the sample the text size should be set beforehand. 

So how can I determine the initial text size to make the autosizing work? Thanks in advance.

**Comment by AndroidDeveloperLB** [comment]
As the name suggests, that's the text size.
If the size is too large to fit in its boundaries, it auto-resizes itself to a size that does fit.

**Comment by storix** [comment]
Thank you for the quick reply. But what if the text size is too small, it won't auto-resize itself, right?

**Comment by AndroidDeveloperLB** [comment]
If you set it to be small, it will be this size or smaller.

**Comment by storix** [comment]
Ok, I'm setting now the text size to the same value as the height constraint and it seems to work fine.

**Comment by AndroidDeveloperLB** [comment]
Careful not to set it too large. I think on some Android versions it can
have GPU memory issues

On 11 Nov 2016 14:15, "Stan Mots" <notifications@github.com> wrote:

Ok, I'm setting now the text size to the same value as the height
constraint and it seems to work fine.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/AndroidDeveloperLB/AutoFitTextView/issues/40#issuecomment-259945480>,
or mute the thread

**Comment by storix** [comment]
Thanks for the warning. Yeah, I heard about this issue with hardware acceleration. In my case it won't be that large.
