### ISSUE TITLE
License is missing copyright

### ISSUE THREAD

**Issue by etanhatch** [AndroidDeveloperLB/AutoFitTextView#53]
In order to be a correct license, you'd need to a dd a copyright statement, like:

Copyright 2020 Me Person

**Comment by AndroidDeveloperLB** [comment]
I don't need it. Do whatever you wish with it.

**Comment by CrackerKSR** [comment]
Hi @AndroidDeveloperLB , I could not find a wayt to contact you :/ although You are everywhere on stackoverflow's android and webp topics :D. 
I saw your kotlin code for extracting frames from animated webp in android. It is working in kotlin. And that's where my struggle ends,  But I stuck with java and kotlin interoperability. I can invoke methods from kotlin in java but not vice versa. Thats why I can't use GlideApp.with() in the kotlin or if I make the module to use It I cannot call java (because encoders classes are in java which I found on github).

It is easy to mixing java kotlin but it works well in andorid studio and I am wokring on RN module which has issue in android studio as it not root project so some files are missing which  android looks for.

With humble request if you can convert your kotlin code into java it would be awesome and life savier. 

Well one of below will solve my proble completly 
 if you can share the code snippet for encoding bitmaps into animated webp.
 OR if you can convert your code into java.

if you well say I will copy your snippets here 

😞plz help

**Comment by AndroidDeveloperLB** [comment]
@CrackerKSR I don't write new code in Java anymore. Only maintain old one, and even then I convert. 
You should do it too.
Java on Android doesn't progress at all compared to Kotlin. There is no valid competition between them.

**Comment by CrackerKSR** [comment]
I understand thats why I said if you can write encoding code for animated webp (in kotlin) then I dont need to use java . The encoding code is in Java and I tried converting that into kotlin but many errors are their. 
Ok no problem. Thanks for replying :)

**Comment by AndroidDeveloperLB** [comment]
@CrackerKSR Why do you write here instead of where you've found about it? Here it's not related at all to WEBP...
