### ISSUE TITLE
Resizing getting always smaller

### ISSUE THREAD

**Issue by thomaslc66** [AndroidDeveloperLB/AutoFitTextView#9]
Hi, i'm using your library that i found very usefull. But i've some problem with it. I'm making a back and forth between two activites and every time i came back on the first one the text is getting smaller and smaller and smaller again. Is it possible to stop this?? and with big text size like 150sp is it possible to erase the font padding top and bottom??

PS: I think import android.annotation.TargetApi is deprecated

**Comment by BrianErikson** [comment]
I just ran into this problem, and it was because the xml attributes `android:layout_width` and `android:layout_height` were set to `wrap_content`. Make sure you use `fill_parent` to ensure the class has room to resize.

Also, @AndroidDeveloperLB, Thank you very much for this useful class. I'm surprised Android doesn't have something like this natively yet.

**Comment by AndroidDeveloperLB** [comment]
@BrianErikson Sadly, most of it isn't mine, so I can barely help. 
I've even found some issues myself, and posted about it on the main page, hoping someone else would have some time to investigate it.

**Comment by AndroidDeveloperLB** [comment]
@thomaslc66 Did you find a way to fix it? or reproduce it?

**Comment by thomaslc66** [comment]
Hi, yes i've find a way to fix it, but without your library.
To solve it. i put my textView to fill parent, then i take the height and the with of the parent, after this i use display Mertrics to find the resolution. Then i calculte text size in sp depending on the with and height avaliable and the resolution of the phone and it fits...

**Comment by AndroidDeveloperLB** [comment]
Nice, can you share the code?
